# Generated by Django 5.2.17 on 2026-09-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_late_deduction_attendance_late_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('ON_TIME', 'On Time'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('COMPLETED', 'Completed')], default='ON_TIME', max_length=20),
        ),
    ]
