# Generated by Django 5.2.17 on 2026-09-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_salaryslip_daily_rate_salaryslip_days_in_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='absent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='late_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='late_salary_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='total_late_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='total_late_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='working_days',
            field=models.IntegerField(default=26),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='days_in_month',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Other deductions', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='leave_days_deducted',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='leave_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
