# Generated by Django 5.2.17 on 2026-09-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_salaryslip_absent_days_salaryslip_late_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='half_days',
            field=models.IntegerField(default=0),
        ),
    ]
