# Generated by Django 5.2.17 on 2026-09-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift_end_time',
            field=models.TimeField(blank=True, help_text='Custom shift end time', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shift_start_time',
            field=models.TimeField(blank=True, help_text='Custom shift start time', null=True),
        ),
    ]
